[general]
import = ["theme.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[scrolling]
history = 50000
multiplier = 3

[window]
decorations = "None"
opacity = 1.0
startup_mode = "Maximized"
class = { general = "Alacritty", instance = "Alacritty" }
padding = { x = 5, y = 5 }

[font]
size = 18.0
normal = { family = "Iosevka NFM", style = "Regular" }
bold = { family = "Iosevka NFM", style = "Bold" }
italic = { family = "Iosevka NFM", style = "Italic" }
bold_italic = { family = "Iosevka NFM", style = "Bold Italic" }

[cursor]
unfocused_hollow = true
style = { blinking = "On", shape = "Block" }
vi_mode_style = { blinking = "On", shape = "Block" }

[keyboard]
bindings = [{ key = "Enter", mods = "Control", action = "ToggleFullscreen" }]
